# Generated by Django 6.0.4 on 2026-05-02 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlesson',
            name='document',
            field=models.FileField(blank=True, upload_to='files/lessons/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'docm', 'odt', 'pdf'])], verbose_name='Document file'),
        ),
        migrations.AddField(
            model_name='newlesson',
            name='presentation',
            field=models.FileField(blank=True, upload_to='files/lessons/presentations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pptm', 'pptx', 'odp', 'key', 'pdf'])], verbose_name='Presentation file'),
        ),
        migrations.AddField(
            model_name='newlesson',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='URL to Youtube video'),
        ),
    ]
