# Generated by Django 6.0.4 on 2026-05-02 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_newlesson_document_newlesson_presentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlesson',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of publish'),
        ),
    ]
