# Generated by Django 6.0.4 on 2026-05-02 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_newlesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlesson',
            name='typ',
            field=models.CharField(choices=[('video', 'Video lesson'), ('presentation', 'Presentation'), ('document', 'Document')], default=django.utils.timezone.now, max_length=50, verbose_name='Type of lesson'),
            preserve_default=False,
        ),
    ]
