# Generated by Django 6.0.4 on 2026-05-03 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_newlesson_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlesson',
            name='document',
            field=models.FileField(blank=True, upload_to='lessons/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'docm', 'odt', 'pdf'])], verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='newlesson',
            name='presentation',
            field=models.FileField(blank=True, upload_to='lessons/presentations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pptm', 'pptx', 'odp', 'key', 'pdf'])], verbose_name='Presentation file'),
        ),
    ]
