# Generated by Django 6.0.4 on 2026-05-03 05:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_newlesson_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of lesson')),
                ('typ', models.CharField(choices=[('video', 'Video lesson'), ('presentation', 'Presentation'), ('document', 'Document')], max_length=50, verbose_name='Type of lesson')),
                ('video_url', models.URLField(blank=True, verbose_name='URL to Youtube video')),
                ('presentation', models.FileField(blank=True, upload_to='lessons/presentations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pptm', 'pptx', 'odp', 'key', 'pdf'])], verbose_name='Presentation file')),
                ('document', models.FileField(blank=True, upload_to='lessons/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'docm', 'odt', 'pdf'])], verbose_name='Document file')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of publish')),
            ],
        ),
        migrations.DeleteModel(
            name='NewLesson',
        ),
    ]
