# Generated by Django 6.0.4 on 2026-05-03 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_delete_newlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='status_typ',
            field=models.CharField(choices=[('video', 'Video lesson'), ('presentation', 'Presentation'), ('document', 'Document')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
