# Generated by Django 6.0.4 on 2026-05-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_reject_reason_lesson_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status_title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='status_typ',
        ),
    ]
