# Generated by Django 6.0.5 on 2026-06-01 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, upload_to='lessons/docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docxpdf'])], verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presentation',
            field=models.FileField(blank=True, upload_to='lessons/presentations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx', 'pdf'])], verbose_name='Presentation file'),
        ),
    ]
