# Generated by Django 6.0.5 on 2026-06-08 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lesson_document_alter_lesson_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of publish'),
        ),
    ]
