# Generated by Django 6.1 on 2026-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('algebra', 'Algebra'), ('geometry', 'Geometry'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('it', 'It'), ('other', 'Other')], default=1, max_length=150, verbose_name='Subject of lesson'),
            preserve_default=False,
        ),
    ]
