# Generated by Django 6.0.5 on 2026-05-19 08:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of solution')),
                ('task_url', models.URLField(blank=True, null=True, verbose_name='URL to task')),
                ('url_github', models.URLField(verbose_name='URL to Github repo or tag(release)')),
                ('url_gitlab', models.URLField(blank=True, null=True, verbose_name='URL to Gitlab repo or tag(release)')),
                ('url_dropbox', models.URLField(blank=True, null=True, verbose_name='URL to Dropbox files')),
                ('url_googledrive', models.URLField(blank=True, null=True, verbose_name='URL to Google Drive files')),
                ('url_mega', models.URLField(blank=True, null=True, verbose_name='URL to Mega Drive files')),
                ('torrent', models.FileField(blank=True, null=True, upload_to='solutions/torrent', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['torrent'])], verbose_name='.torrent file')),
                ('date_task', models.DateField(verbose_name='Date when task was published')),
                ('date_published', models.DateField(default=django.utils.timezone.now, verbose_name='Date of publish')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
