# Generated by Django 6.0.5 on 2026-05-15 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoitanyway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letsdoitanyway',
            name='torrent',
            field=models.FileField(blank=True, null=True, upload_to='letsdoitanyway/torrent', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['torrent'])], verbose_name='.torrent file'),
        ),
    ]
