# Generated by Django 6.0.5 on 2026-05-30 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Time of year of olympiad')),
                ('description', models.TextField(verbose_name='Description of olympiad')),
                ('subject', models.CharField(choices=[('math', 'Math'), ('physics', 'Physics')], max_length=25, verbose_name='Subject of olympiad')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of publish')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name="Text of olympiad's task")),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='olympiads.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadTaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name="Text of olympiad's answer")),
                ('is_true', models.BooleanField(default=False, verbose_name='Is answer true?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='olympiads.olympiadtask')),
            ],
        ),
    ]
