# Generated by Django 6.0.5 on 2026-05-30 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date of publish'),
        ),
    ]
