# Generated by Django 6.0.5 on 2026-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_alter_olympiad_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=25),
        ),
    ]
