# Generated by Django 6.0.5 on 2026-06-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_olympiad_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='user',
        ),
    ]
