# Generated by Django 6.0.5 on 2026-05-21 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of news')),
                ('text', models.TextField(verbose_name='Text of news')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of publish')),
            ],
        ),
    ]
