# Generated by Django 6.0.5 on 2026-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='icon',
            field=models.CharField(default='fa-solid fa-cubes', max_length=120, verbose_name='FA icon'),
        ),
    ]
