# Generated by Django 6.0.4 on 2026-05-06 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of lesson')),
                ('description', models.CharField(max_length=200, verbose_name='Small text of article')),
                ('image', models.FileField(upload_to='', verbose_name='Image for article')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of publish')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
            ],
        ),
    ]
