# Generated by Django 6.0.5 on 2026-05-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_user_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_by',
        ),
    ]
