# Generated by Django 6.0.4 on 2026-05-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
