# Generated by Django 6.1 on 2026-09-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_remove_olympiad_user'),
        ('profile', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_olympiads',
            field=models.ManyToManyField(blank=True, related_name='completed_olympiads', to='olympiads.olympiad'),
        ),
    ]
